### ISSUE TITLE
Preprocessing not working

### ISSUE THREAD

**Issue by Czechball** [donadigo/TMTrackNN#1]
Hello,
I tried to generate my own datasets to train using your preprocessing.py script, but got a strange error. Here's the command output:
```
[czechball@uzlabina-server TMTrackNN]$ python3.7 preprocessing.py -i testreplays/ -o testoutput/
-- Creating pattern data...
-- Scaling position data..
Traceback (most recent call last):
  File "preprocessing.py", line 175, in <module>
    pickle.dump(fit_data_scaler(train_data), scaler_file)
  File "/home/czechball/TMGEN/TMTrackNN/core/track_utils.py", line 205, in fit_data_scaler
    scaler.fit(X)
  File "/usr/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 339, in fit
    return self.partial_fit(X, y)
  File "/usr/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 373, in partial_fit
    force_all_finite="allow-nan")
  File "/usr/lib/python3.7/site-packages/sklearn/utils/validation.py", line 540, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```

The folder "testreplays" contains four replays of fullspeed tracks:
```
-rw-r--r--  1 czechball czechball 289776 Dec 13 13:43 1.gbx
-rw-r--r--  1 czechball czechball  79211 Dec 13 13:43 2.gbx
-rw-r--r--  1 czechball czechball  44999 Dec 13 13:43 3.Gbx
-rw-r--r--  1 czechball czechball 175370 Dec 13 13:43 4.gbx
```

Here are the replays themselves:
[testreplays.zip](https://github.com/donadigo/TMTrackNN/files/3960829/testreplays.zip)

I'm using Python 3.7.5 on Arch Linux `5.3.11-arch1-1` and the same error has occured also on Debian 10 and Windows 10 WSL Debian 10.

**Comment by donadigo** [comment]
For some reason I made it so the code checks for `.Replay.Gbx` extension at the end of the file and that's why the script fails for you. You have to rename the files to be exactly `some name here.Replay.Gbx` (and not `.replay.gbx` nor `.replay.Gbx` etc. It makes sense though to include a message if none files were processed and change the code to process all Gbx files.

**Comment by Czechball** [comment]
Nice, it works! Thanks for your help.

By the way, I'm very impressed by the results when generating tech maps from your models. They're almost flawless! I'm hoping to achieve the same results with fullspeed tracks.
