### ISSUE TITLE
Downloading replays from TMX

### ISSUE THREAD

**Issue by Czechball** [donadigo/TMTrackNN#2]
Hey, it's me again...

In your dataset description, you mentioned that the file `train_data.pkl` contains rougly 3000 tech tracks from TMX. My question is, how did you get them? Is there any API available or did you just write a script and parsed the HTML?

**Comment by donadigo** [comment]
I wrote a browser extension that put a "Download All" button on the site and I just set the filters (tech, 1 min, 100 tracks per page) and scrubbed through ~30 pages. If you want I can provide this too.

**Comment by nohcnamp** [comment]
i'm interfering to the discussion, i think this would be interesting to share this browser extension to the community and particularly to the site maintainer (eyebo or ozon i think but i'm not sure)? You might want to concact him (the owner) on discord or else so this can be added to the website...
[link](https://discordapp.com/invite/uRwvByS) to the discord of the website
EDIT: link and typo

**Comment by Czechball** [comment]
That's nice, I thought it would be a python script using beautiful soup or something like that... Mind sharing the extension? I would love to try it.

And yea, I think that it's a good idea to also share it with the TMX community.

**Comment by donadigo** [comment]
It's now available here: https://github.com/donadigo/TMXDownloader
